Kenya_rentals/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from rentalsapp import views




urlpatterns = [
    path('', include('rentalsapp.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rentalsapp/urls.py
from django.contrib import admin
from django.urls import path
from rentalsapp import views




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('about/', views.about,name='about'),
    path('agents/', views.agents, name='agents'),
    path('services/', views.services, name='services'),
    path('properties/', views.properties, name='properties'),
    path('starter/', views.starter, name='starter'),
    path('contact/', views.contact, name='contact'),
    path('agentregister/', views.agentregister, name='agentregister'),
    path('agents/', views.agents, name='agents'),
    path('agentlogin/', views.agentlogin, name='agentlogin'),
    path('houseuploads/', views.houseuploads, name='houseuploads'),
    path('showproperties/', views.showproperties, name='showproperties'),
    path('housedelete/<int:id>', views.housedelete, name='housedelete'),
    path('houseedit/<int:id>', views.houseedit, name='houseedit'),
    path('houseupdate/<int:id>', views.houseupdate, name='houseupdate'),
    path('propertysingle/', views.propertysingle, name='propertysingle'),
    path('searchhouse/', views.searchhouse, name='searchhouse'),
    path('pay/', views.pay, name='pay'),
    path('stk/', views.stk, name='stk'),
]

rentalsapp/models.py
from django.db import models

# Create your models here.
class ImageModel(models.Model):
    image = models.ImageField(upload_to='images/')
    rent = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    area =models.CharField(max_length=50)
    beds = models.CharField(max_length=50)
    baths = models.CharField(max_length=50)
    garage = models.CharField(max_length=50)

    def __str__(self):
        return self.title

class Agent(models.Model):
    name = models.CharField(max_length=50)
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class ContactModel(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    subject = models.CharField(max_length=50)
    message = models.TextField()

    def __str__(self):
        return self.name

rentalsapp/forms.py
from django import forms
from rentalsapp.models import ImageModel

class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = ImageModel
        fields = ['image','rent','title','area','beds','baths','garage',]

rentalsapp/views.py
import requests
import json

from django.shortcuts import render, redirect
from django.http import HttpResponse
from requests.auth import HTTPBasicAuth

from rentalsapp.credentials import MpesaAccessToken, LipanaMpesaPassword
from rentalsapp.forms import ImageUploadForm
from rentalsapp.models import ImageModel,Agent,ContactModel


# Create your views here.

def home(request):
    images = ImageModel.objects.all()
    return render(request,'index.html',{'images':images})

def about(request):
    return render(request,'about.html')

def properties(request):
    images = ImageModel.objects.all()
    return render(request,'properties.html',{'images':images})

def services(request):
    return render(request,'services.html')

def agents(request):
    return render(request,'agents.html')

def starter(request):
    return render(request,'starter-page.html')
def agentregister(request):
    if request.method == 'POST':
        agent=Agent(
            name=request.POST['name'],
            username=request.POST['username'],
            password=request.POST['password'],
        )
        agent.save()
        return redirect('/agentlogin')
    else:
        return render(request,'agent-register.html')

def agentlogin(request):
    if request.method == 'POST':
        if Agent.objects.filter(username=request.POST['username'],
                                password=request.POST['password']).exists():
            agent = Agent.objects.get(username=request.POST['username'],
                                      password=request.POST['password'],
            )
            return redirect('/houseuploads/',context={'agent':agent})
        else:
            return render(request,'agent-login.html')
    else:
        return render(request,'agent-login.html')

def showproperties(request):
    images = ImageModel.objects.all()
    return render(request,'show-properties.html',{'images':images})

def housedelete(request,id):
    image = ImageModel.objects.get(id=id)
    image.delete()
    return redirect('/showproperties')

def propertysingle(request):
    images = ImageModel.objects.all()
    return render(request,'property-single.html')

def houseedit(request,id):
    editimage = ImageModel.objects.get(id=id)
    return render(request,'house-edit.html',{'image':editimage})

def houseuploads(request):
    if request.method == "POST":
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/showproperties')
    else:
        form = ImageUploadForm()
        return render(request,'house-uploads.html',{'form':form})

def houseupdate(request,id):
    updateinfo = ImageModel.objects.get(id=id)
    form = ImageUploadForm(request.POST, instance=updateinfo)
    if form.is_valid():
        form.save()
        return redirect('/showproperties')
    else:
        return render(request,'house-edit.html')

def searchhouse(request):
    query = request.GET.get('query', '')
    category = request.GET.get('category', '')

    if query and category:
        houses = ImageModel.objects.filter(title__icontains=query, beds__iexact=category)
    else:
        houses = []
    return render(request,'search-result.html',{'houses':houses,'query':query,'category':category})

def contact(request):
    if request.method == "POST":
        mycontact=ContactModel(
            name=request.POST['name'],
            email=request.POST['email'],
            subject=request.POST['subject'],
            message=request.POST['message'],
        )
        mycontact.save()
        return render(request,'contact.html')
    else:
        return render(request,'contact.html')

def pay(request):
    return render(request,'pay.html')

def stk(request):
    if request.method =="POST":
        phone = request.POST['phone']
        amount = request.POST['amount']
        access_token = MpesaAccessToken.validated_mpesa_access_token
        api_url = "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
        headers = {"Authorization": "Bearer %s" % access_token}
        request = {
            "BusinessShortCode": LipanaMpesaPassword.Business_short_code,
            "Password": LipanaMpesaPassword.decode_password,
            "Timestamp": LipanaMpesaPassword.lipa_time,
            "TransactionType": "CustomerPayBillOnline",
            "Amount": amount,
            "PartyA": phone,
            "PartyB": LipanaMpesaPassword.Business_short_code,
            "PhoneNumber": phone,
            "CallBackURL": "https://sandbox.safaricom.co.ke/mpesa/",
            "AccountReference": "Rentals",
            "TransactionDesc": "Life assurance"
        }
        response = requests.post(api_url, json=request, headers=headers)
        print(response.json())
        return HttpResponse("Success")

templates/agent-login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>login</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</head>
<body>
    <section class="vh-100" style="background-color: #2eca6a;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-xl-10">
        <div class="card" style="border-radius: 1rem;">
          <div class="row g-0">
            <div class="col-md-6 col-lg-5 d-none d-md-block">
              <img src="https://images.pexels.com/photos/7599735/pexels-photo-7599735.jpeg?auto=compress&cs=tinysrgb&w=600"
                alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
            </div>
            <div class="col-md-6 col-lg-7 d-flex align-items-center">
              <div class="card-body p-4 p-lg-5 text-black">

                <form method="POST" action="{% url 'agentlogin' %}">
                    {% csrf_token %}

                  <div class="d-flex align-items-center mb-3 pb-1">
                    <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                    <span class="h1 fw-bold mb-0">Kenya Rentals</span>
                  </div>

                  <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Agent Sign-in</h5>

                  <div data-mdb-input-init class="form-outline mb-4">
                    <input type="text" name="username" id="form2Example17" class="form-control form-control-lg" />
                    <label class="form-label" for="form2Example17">Username</label>
                  </div>

                  <div data-mdb-input-init class="form-outline mb-4">
                    <input type="password" name="password" id="form2Example27" class="form-control form-control-lg" />
                    <label class="form-label" for="form2Example27">Password</label>
                  </div>

                  <div class="pt-1 mb-4">
                    <button data-mdb-button-init data-mdb-ripple-init class="btn btn-dark btn-lg btn-block" type="submit">Login</button>
                  </div>

                  <a class="small text-muted" href="#!">Forgot password?</a>
                  <p class="mb-5 pb-lg-2" style="color: #393f81;">Don't have an account? <a href="{% url 'agentregister' %}"
                      style="color: #393f81;">Register here</a></p>
                  <a href="#!" class="small text-muted">Terms of use.</a>
                  <a href="#!" class="small text-muted">Privacy policy</a>
                </form>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

</body>
</html>

templates/agent-register.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Register</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</head>
<body>

<section class="vh-100" style="background-color: #2eca6a; ">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-12 " >
        <div class="card text-black w-75 m-auto h-75" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1 mt-3 h-50">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Create Agent Account</p>

                <form class="mx-1 mx-md-4" method="POST" 4>
                    {% csrf_token %}

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div data-mdb-input-init class="form-outline flex-fill mb-0">
                      <input type="text" name="name" id="form3Example1c" class="form-control" required/>
                      <label class="form-label" for="form3Example1c">Your Name</label>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                    <div data-mdb-input-init class="form-outline flex-fill mb-0">
                      <input type="text" name="username" id="form3Example3c" class="form-control" required />
                      <label class="form-label" for="form3Example3c">Your username</label>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                    <div data-mdb-input-init class="form-outline flex-fill mb-0">
                      <input type="password" name="password"  id="form3Example4c" class="form-control" required/>
                      <label class="form-label" for="form3Example4c">Password</label>
                    </div>
                  </div>
                  <div class="form-check d-flex justify-content-center mb-5">
                    <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3c" />
                    <label class="form-check-label" for="form2Example3">
                      I agree all statements in <a href="#!">Terms of service</a>
                    </label>
                  </div>

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <button  type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-lg">Register</button>
                  </div>

                    <a href="{% url 'agentlogin' %}">Already have an account?</a> <br><br>

                </form>

              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://images.pexels.com/photos/7599735/pexels-photo-7599735.jpeg?auto=compress&cs=tinysrgb&w=600"
                  class="img-fluid h-100" alt="Sample image">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

</body>
</html>

templates/agents.html
{% extends 'starter-page.html' %}
{% load static %}
{% block body %}
    <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">

      <a href="{% url 'home' %}" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1 class="sitename">Kenya<span>Rentals</span></h1>
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'services' %}">Services</a></li>
          <li><a href="{% url 'properties' %}">Properties</a></li>
          <li><a href="{% url 'agents' %}" class="active">Agents</a></li>
          <li><a href="{% url 'contact' %}">Contact</a></li>
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>
    </div>
  </header>

  <main class="main">

    <!-- Page Title -->
    <div class="page-title" data-aos="fade">
      <div class="heading">
        <div class="container">
          <div class="row d-flex justify-content-center text-center">
            <div class="col-lg-8">
              <h1>Agents</h1>
              <p class="mb-0">Get in touch with any one of our agents.They will answer any of your queries regarding the property. They can also arrange a site visit to the property to ensure you are full satisfied before making any payment decisions. Ensure to contact them before making any payment for booking a house.</p>
            </div>
          </div>
        </div>
      </div>
        <div class="container">
            <a href="{% url 'agentlogin' %}">Click to log in as agent</a>
        </div>
    </div><!-- End Page Title -->

    <!-- Agents Section -->
    <section id="agents" class="agents section">

      <div class="container">

        <div class="row gy-5">

          <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="100">
            <div class="member">
              <div class="pic"><img src="{% static 'assets/img/team/team-1.jpg' %}" class="img-fluid" alt=""></div>
              <div class="member-info">
                <h4>Walter White</h4>
                <span>Chief Executive Officer</span>
                <div class="social">
                  <a href=""><i class="bi bi-twitter-x"></i></a>
                  <a href=""><i class="bi bi-facebook"></i></a>
                  <a href=""><i class="bi bi-instagram"></i></a>
                  <a href=""><i class="bi bi-linkedin"></i></a>
                </div>
              </div>
            </div>
          </div><!-- End Team Member -->

          <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="200">
            <div class="member">
              <div class="pic"><img src="{% static 'assets/img/team/team-2.jpg' %}" class="img-fluid" alt=""></div>
              <div class="member-info">
                <h4>Sarah Jhonson</h4>
                <span>Rent Manager</span>
                <div class="social">
                  <a href=""><i class="bi bi-twitter-x"></i></a>
                  <a href=""><i class="bi bi-facebook"></i></a>
                  <a href=""><i class="bi bi-instagram"></i></a>
                  <a href=""><i class="bi bi-linkedin"></i></a>
                </div>
              </div>
            </div>
          </div><!-- End Team Member -->

          <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="300">
            <div class="member">
              <div class="pic"><img src="{% static 'assets/img/team/team-3.jpg' %}" class="img-fluid" alt=""></div>
              <div class="member-info">
                <h4>William Anderson</h4>
                <span>Sale manager<br></span>
                <div class="social">
                  <a href=""><i class="bi bi-twitter-x"></i></a>
                  <a href=""><i class="bi bi-facebook"></i></a>
                  <a href=""><i class="bi bi-instagram"></i></a>
                  <a href=""><i class="bi bi-linkedin"></i></a>
                </div>
              </div>
            </div>
          </div><!-- End Team Member -->

        </div>

      </div>

    </section><!-- /Agents Section -->

  </main>

{% endblock %}

templates/contact.html
{% extends 'starter-page.html' %}
{% load static %}
{% block body %}
    <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">

      <a href="{% url 'home' %}" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1 class="sitename">Kenya<span>Rentals</span></h1>
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'services' %}">Services</a></li>
          <li><a href="{% url 'properties' %}">Properties</a></li>
          <li><a href="{% url 'agents' %}" >Agents</a></li>
          <li><a href="{% url 'contact' %}" class="active">Contact</a></li>
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>

    </div>
  </header>

  <main class="main">

    <!-- Page Title -->
    <div class="page-title" data-aos="fade">
      <div class="heading">
        <div class="container">
          <div class="row d-flex justify-content-center text-center">
            <div class="col-lg-8">
              <h1>Contact</h1>
              <p class="mb-0">You can visit us at our offices or reach out to us through the communication channels listed below. Ensure to follow
              us on our social media to be updated of our latest developments</p>
            </div>
          </div>
        </div>
      </div>
      <nav class="breadcrumbs">
        <div class="container">
          <ol>
            <li><a href="{% url 'home' %}">Home</a></li>
            <li class="current">Contact</li>
          </ol>
        </div>
      </nav>
    </div><!-- End Page Title -->

    <!-- Contact Section -->
    <section id="contact" class="contact section">

      <div class="container" data-aos="fade-up" data-aos-delay="100">

        <div class="mb-4" data-aos="fade-up" data-aos-delay="200">
          <iframe style="border:0; width: 100%; height: 270px;" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d48389.78314118045!2d-74.006138!3d40.710059!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25a22a3bda30d%3A0xb89d1fe6bc499443!2sDowntown%20Conference%20Center!5e0!3m2!1sen!2sus!4v1676961268712!5m2!1sen!2sus" frameborder="0" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div><!-- End Google Maps -->

        <div class="row gy-4">

          <div class="col-lg-4">
            <div class="info-item d-flex" data-aos="fade-up" data-aos-delay="300">
              <i class="bi bi-geo-alt flex-shrink-0"></i>
              <div>
                <h3>Address</h3>
                <p>Ngong' Road, Kilimani, Peace Suites 6 </p>
              </div>
            </div><!-- End Info Item -->

            <div class="info-item d-flex" data-aos="fade-up" data-aos-delay="400">
              <i class="bi bi-telephone flex-shrink-0"></i>
              <div>
                <h3>Call Us</h3>
                <p>+254790931766</p>
              </div>
            </div><!-- End Info Item -->

            <div class="info-item d-flex" data-aos="fade-up" data-aos-delay="500">
              <i class="bi bi-envelope flex-shrink-0"></i>
              <div>
                <h3>Email Us</h3>
                <p>info@krentals.co.ke</p>
              </div>
            </div><!-- End Info Item -->

          </div>

          <div class="col-lg-8">
            <form action="{% url 'contact' %}" method="post" class="php-email-form" data-aos="fade-up" data-aos-delay="200">
              <div class="row gy-4">

                <div class="col-md-6">
                  <input type="text" name="name" class="form-control" placeholder="Your Name" required="">
                </div>

                <div class="col-md-6 ">
                  <input type="email" class="form-control" name="email" placeholder="Your Email" required="">
                </div>

                <div class="col-md-12">
                  <input type="text" class="form-control" name="subject" placeholder="Subject" required="">
                </div>

                <div class="col-md-12">
                  <textarea class="form-control" name="message" rows="6" placeholder="Message" required=""></textarea>
                </div>

                <div class="col-md-12 text-center">
                  <div class="loading">Loading</div>
                  <div class="error-message"></div>
                  <div class="sent-message">Your message has been sent. Thank you!</div>

                  <button type="submit">Send Message</button>
                </div>

              </div>
            </form>
          </div><!-- End Contact Form -->

        </div>

      </div>

    </section><!-- /Contact Section -->

  </main>
	
{% endblock %}

templates/house-edit.html
{% extends 'starter-page.html' %}
{% load static %}
{% block body %}
    <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">

      <a href="{% url 'home' %}" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1 class="sitename">Kenya<span>Rentals</span></h1>
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a href="{% url 'agents' %}">Agent Logout</a></li>
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>
    </div>
  </header>
    <main class="main">
        <div class="page-title" data-aos="fade">
      <div class="heading">
        <div class="container pb-0 mb-0">
          <div class="row d-flex justify-content-center text-center">
            <div class="col-lg-8">
              <h1>Update House</h1>
              <p class="mb-0">We have a select range of properties you can choose from. Chose from 1,2,3 bedroom. You need a bungalow? No worries
              All your housing needs are taken care of by us</p>
            </div>
          </div>
        </div>
      </div>
    </div><!-- End Page Title -->

    <form method="post" action="/houseupdate/{{ image.id }}"  enctype="multipart/form-data" class="text-center m-5 mb-4">
        {% csrf_token %}

         <h2>Update Image</h2>
        <p>
            <label for="id_image">Image:</label>
            <input type="file" name="image" value="{{ image.image.url}}" id="name"  required="">
        </p>

        <p>
            <label for="id_rent">Rent:</label>
            <input type="text" value="{{ image.rent }}" name="rent">
        </p>
        <p>
            <label for="id_title">Title:</label>
            <input type="text" value="{{ image.title }}" name="title">
        </p>
        <p>
            <label for="id_area">Area:</label>
            <input type="text" value="{{ image.area }}" name="area">
        </p>
        <p>
            <label for="id_beds">Beds:</label>
            <input type="text" value="{{ image.beds }}" name="beds">
        </p>
        <p>
            <label for="id_baths">Baths:</label>
            <input type="text" value="{{ image.baths }}" name="baths">
        </p>
        <p>
            <label for="id_garages">Garage:</label>
            <input type="text" value="{{ image.garage }}" name="garage">
        </p>

        <button type="submit">Update</button>
        <a href="{% url 'showproperties' %}" class="btn btn-warning">Display images</a>
    </form>
    </main>


{% endblock %}

templates/house-uploads.html
{% extends 'starter-page.html' %}
{% load static %}
{% block body %}
    <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">

      <a href="{% url 'home' %}" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1 class="sitename">Kenya<span>Rentals</span></h1>
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a href="{% url 'agents' %}">Agent Logout</a></li>
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>
    </div>
  </header>
    <main class="main">
        <div class="page-title" data-aos="fade">
      <div class="heading">
        <div class="container pb-0 mb-0">
          <div class="row d-flex justify-content-center text-center">
            <div class="col-lg-8">
              <h1>Upload New Listings</h1>
              <p class="mb-0">We have a select range of properties you can choose from. Chose from 1,2,3 bedroom. You need a bungalow? No worries
              All your housing needs are taken care of by us</p>
            </div>
          </div>
        </div>
      </div>
    </div><!-- End Page Title -->

    <form method="post" enctype="multipart/form-data" class="text-center d-block m-auto mb-4">
        {% csrf_token %}

         <h2>Upload Image</h2>
        {{ form.as_p }}
        <button type="submit">Upload</button>
        <a href="{% url 'showproperties' %}" class="btn btn-warning">Display images</a>
    </form>
    </main>


{% endblock %}

templates/pay.html
{% extends 'starter-page.html' %}
{% load static %}
{% block body %}

 <header id="header" class="header d-flex align-items-center fixed-top mb-5">
    <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">

      <a href="{% url 'home' %}" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1 class="sitename">Kenya<span>Rentals</span></h1>
      </a>

    </div>
  </header>

<div class="justify-content-around">
<div class="text-center mt-5  ps-5 pe-5">
<h2>Make a Payment</h2>

<form class="pb-4" method="post" action="{% url 'stk' %}">
  {% csrf_token %}
    <label for="phone">Phone Number :</label><br>
    <input class="form-control" type="number" id="phone" name="phone" value="254" placeholder="Phone Number">
    <br><br>

    <label for="amount">Amount :</label> <br>
    <input class="form-control" type="text" id="amount" name="amount" placeholder="Amount">
    <br><br>
  <button class="btn btn-success" type="submit">Submit</button>
</form>
</div>
</div>

{% endblock %}

templates/show-properties.html
{% extends 'starter-page.html' %}
{% load static %}
{% block body %}
<main class="main">
  <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl position-relative mb-5 d-flex align-items-center justify-content-between">

      <a href="{% url 'home' %}" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1 class="sitename">Kenya<span>Rentals</span></h1>
      </a>
      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a href="{% url 'agents' %}">Agent Logout</a></li>
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>

    </div>
  </header>
<div class="pt-5">
<h2 class="text-center mt-5">New Properties</h2>
<div class="container">
<div style="display: flex; justify-content:space-between; flex-wrap: wrap">
    {% for image in images %}
        <div class="col mb-2">
            <img src="{{ image.image.url }}" alt="Uploaded Image" style="width: 300px;height:300px"> <br>
            <p><strong>Rent :</strong>{{ image.rent }}</p>
            <p><strong>Title :</strong>{{ image.title }}</p>
            <p><strong>Area :</strong>{{ image.area }}</p>
            <p><strong>Beds :</strong>{{ image.beds }}</p>
            <p><strong>Bathrooms :</strong>{{ image.baths }}</p>
            <p><strong>Garage :</strong>{{ image.garage }}</p>
            <a href="/housedelete/{{ image.id }}" class="btn btn-outline-danger">DELETE</a>
            <a href="/houseedit/{{ image.id }}" class="btn btn-outline-danger">EDIT</a>
        </div>

    {% endfor %}

</div>

</div>
</div>
</main>
{% endblock %}